pipeline {
    agent any
    options { 
        buildDiscarder(logRotator(numToKeepStr: NUM_BUILDS_TO_KEEP))
        disableConcurrentBuilds()
        timeout(time: NUM_MINUTES_TO_KEEP, unit: 'MINUTES')
    }
    stages {
        stage('setup production') {
            steps {
                ansiblePlaybook (
                  colorized: true,
                  limit: 'python',
                  disableHostKeyChecking: true,
                  inventory: 'ansible/inventory/hosts.yml',
                  playbook: 'ansible/setup.yml'
                )
            }
        }
    }
}